# Generated by Django 2.0.8 on 2018-08-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifications_type',
            new_name='notification_type',
        ),
    ]
