# Generated by Django 2.0.8 on 2018-08-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180811_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='captions',
            new_name='caption',
        ),
    ]
