# Generated by Django 2.0.8 on 2018-08-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
